loadTimeData.data = {
  bestScore: "最佳分数排名 $1 $2 $3",
  bestScoreFlyout: "历史最佳分数: $1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "取消",
  close: "关闭",
  code: "作弊代码激活！",
  codeCheat: "作弊代码激活！ $1",
  codeScoring: "这一轮的得分被取消了",
  endlessBestScore: -1,
  endlessDescriptor: "距离",
  endlessModeTitleInline: "无尽模式:",
  endlessTitle: "无尽模式",
  endlessUnit: "米",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "关于游戏",
  gameCreditsDialogTitle: "关于游戏",
  gameMode: "游戏模式变成了 $1",
  gameModeSelectLabel: "游戏模式",
  gameModeSelectLabelDisabled: "游戏模式(开始新的游戏来改变)",
  gameSettings: "游戏设置",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "高可见度",
  howToPlayButton: "游戏规则",
  howToPlayControllerBoost: "按下“RT”来使用加速",
  howToPlayControllerMovement: "使用遥杆或“D-pad”转向",
  howToPlayControllerRefresh: "按下“LB”和“RB”来重启游戏",
  howToPlayDialogTitle: "游戏规则",
  howToPlayEndless:
    "尽最大努力去滑行，争取获得最好的成绩！",
  howToPlayKeyboardBoost: "按下“F”来使用加速",
  howToPlayKeyboardMovement: "使用方向键或“WASD”键转向",
  howToPlayKeyboardRefresh: "刷新页面来重启游戏",
  howToPlayMouseBoost: "右键来使用加速",
  howToPlayMouseMovement: "移动鼠标来转向",
  howToPlayMouseRefresh: "刷新页面来重启游戏",
  howToPlayTimeTrial:
    "尽可能快地到达终点，收集硬币以减少时间",
  howToPlayTouchBoost: "向下点击两次以使用速度提升",
  howToPlayTouchMovement: "轻扫以转向",
  howToPlayTouchRefresh: "刷新页面来重启游戏",
  howToPlayZigZag: "尽努力去通过这些用旗杆围成的门",
  is_windows_xbox_sku: "错误",
  keyboardAction: "空格键",
  language: "zh",
  lastSelectedMode: "无尽模式",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "大海冲浪",
  menuInfo: "开始游戏",
  mouseAction: "双击",
  newBestScore: "最新记录 $1 $2 $3",
  newGame: "开始新游戏",
  off: "关闭",
  on: "开启",
  overInfo: "再玩一次",
  overTitle: "表现不错！",
  pauseInfo: "继续游戏",
  pauseTitle: "暂停游戏",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "减速",
  resetAllStats: "重置所有数据",
  resetAllStatsDialogText:
    "你确定要重置所有游戏数据吗？",
  resetAllStatsDialogTitle: "重置所有数据",
  share: "分享",
  shareCopy: "复制链接",
  shareLink: "https://game.xiejiayu.com",
  shareLinkCopied: "已复制！",
  skiTheme: "高山滑雪",
  specialThanks: "特别鸣谢:",
  surfTheme: "大海冲浪",
  textdirection: "ltr",
  theme: "游戏模式改变为 $1",
  themeSelectLabel: "游戏模式",
  timetrialBestScore: -1,
  timetrialDescriptor: "时间",
  timetrialModeTitleInline: "计时赛:",
  timetrialTitle: "计时赛",
  timetrialUnit: "s",
  touchAction: "双击",
  zigzagBestScore: -1,
  zigzagDescriptor: "之字形",
  zigzagModeTitleInline: "之字形:",
  zigzagTitle: "之字形",
  zigzagUnit: "大门",
};
